### ISSUE TITLE
[Enhancement] Add global securityContext and podSecurityContext

### ISSUE THREAD

**Issue by zgastley** [runwhen-contrib/helm-charts#48]
**Observation**  
Currently, there exist `securityContext` and `podSecurityContext` configurations for the `runner` section of the Helm chart, which is great. However, in my environment, we need these settings to be applied to all Kubernetes resources. A global setting for these configurations in the Helm chart would be ideal.

 **Current Outcome**  
Chart is missing `securityContext` and `podSecurityContext` configurations on specific resources, notably in the `test-connections.yaml` template. In my environment, we have had to manually mutate these files using security tools to include the necessary security controls.

 **Example (`test-connections.yaml`)**
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: "{{ include \"runwhen-local.fullname\" . }}-test-connection"
  labels:
    {{- include \"runwhen-local.labels\" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['{{ include \"runwhen-local.fullname\" . }}:{{ .Values.runwhenLocal.service.port }}']
  restartPolicy: Never
```
**Note**: The above template does not include securityContext or podSecurityContext configurations.

**Desired Outcome**
- introduce a global securityContext and podSecurityContext configuration in values.yaml, similar to the existing configuration for the runner section.
- Ensure that these global security configurations apply to all pods and containers via Helm templating.

**Benefits**
- Reduces manual intervention when deploying in environments with strict security policies.
- Ensures consistency across all resources.
- Aligns with best practices for secure Kubernetes deployments

**Comment by zgastley** [comment]
On closer inspection, it looks like you guys _do_ have some templates utilizing a ` .Values.podSecurityContext` value but this doesn't appear to be in your values file. 

[Example](https://github.com/runwhen-contrib/helm-charts/blob/main/charts/runwhen-local/templates/local-deployment.yaml#L32) in the `local-deployment.yaml`.

```yaml
spec:
      {{- with .Values.runwhenLocal.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.runwhenLocal.serviceAccount.name }}
      automountServiceAccountToken: true
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
```

Adding the `podSecurityContext` in the `global` section of the `values.yaml` file and then including this in the other pod/deployment files of the template would work as fix here.
